# Generated by Django 6.0.4 on 2026-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_first_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile No'),
        ),
    ]